
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Alignment alignment3;

	private global::Gtk.Image image1;

	private global::Gtk.Label label1;

	private global::Gtk.Alignment alignment4;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button btnPower;

	private global::Gtk.Button btnVolPlus;

	private global::Gtk.Button btnVolMinus;

	private global::Gtk.ComboBox cbInput;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Image image16;

	private global::Gtk.Label label2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.VBox vbox9;

	private global::Gtk.Image image5;

	private global::Gtk.Label label3;

	private global::Gtk.VBox vbox8;

	private global::Gtk.Alignment alignment7;

	private global::Gtk.ComboBox cbBright;

	private global::Gtk.Alignment alignment8;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Alignment alignment5;

	private global::Gtk.Button btnRight;

	private global::Gtk.Alignment alignment6;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Button btnUp;

	private global::Gtk.Button btnSets;

	private global::Gtk.Button btnDown;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.Button btnLeft;

	private global::Gtk.Alignment alignment2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Usenda Software Management");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 25;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		this.hbox3.Add(this.alignment3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.alignment3]));
		w1.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.hbox3.Add(this.image1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.image1]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Usenda Software Management v 1.0");
		this.hbox3.Add(this.label1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label1]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment4.Name = "alignment4";
		this.hbox3.Add(this.alignment4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.alignment4]));
		w4.Position = 3;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		w5.Padding = ((uint)(10));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnPower = new global::Gtk.Button();
		this.btnPower.CanFocus = true;
		this.btnPower.Name = "btnPower";
		this.btnPower.UseUnderline = true;
		global::Gtk.Image w6 = new global::Gtk.Image();
		this.btnPower.Image = w6;
		this.hbox1.Add(this.btnPower);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnPower]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnVolPlus = new global::Gtk.Button();
		this.btnVolPlus.CanFocus = true;
		this.btnVolPlus.Name = "btnVolPlus";
		this.btnVolPlus.UseUnderline = true;
		global::Gtk.Image w8 = new global::Gtk.Image();
		this.btnVolPlus.Image = w8;
		this.hbox1.Add(this.btnVolPlus);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnVolPlus]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnVolMinus = new global::Gtk.Button();
		this.btnVolMinus.CanFocus = true;
		this.btnVolMinus.Name = "btnVolMinus";
		this.btnVolMinus.UseUnderline = true;
		global::Gtk.Image w10 = new global::Gtk.Image();
		this.btnVolMinus.Image = w10;
		this.hbox1.Add(this.btnVolMinus);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnVolMinus]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cbInput = global::Gtk.ComboBox.NewText();
		this.cbInput.AppendText(global::Mono.Unix.Catalog.GetString("HDMI1"));
		this.cbInput.AppendText(global::Mono.Unix.Catalog.GetString("HDMI2"));
		this.cbInput.AppendText(global::Mono.Unix.Catalog.GetString("OPS/HDMI3/DVI-D"));
		this.cbInput.AppendText(global::Mono.Unix.Catalog.GetString("DISPLAYPORT"));
		this.cbInput.Name = "cbInput";
		this.hbox1.Add(this.cbInput);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.cbInput]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.image16 = new global::Gtk.Image();
		this.image16.Name = "image16";
		this.vbox3.Add(this.image16);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image16]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Видео вход");
		this.vbox3.Add(this.label2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.hbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
		w15.PackType = ((global::Gtk.PackType)(1));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 10;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.image5 = new global::Gtk.Image();
		this.image5.Name = "image5";
		this.vbox9.Add(this.image5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.image5]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Яркость");
		this.vbox9.Add(this.label3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label3]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.hbox2.Add(this.vbox9);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox9]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.alignment7 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment7.Name = "alignment7";
		this.vbox8.Add(this.alignment7);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.alignment7]));
		w20.Position = 0;
		// Container child vbox8.Gtk.Box+BoxChild
		this.cbBright = global::Gtk.ComboBox.NewText();
		this.cbBright.AppendText(global::Mono.Unix.Catalog.GetString("Выкл."));
		this.cbBright.AppendText(global::Mono.Unix.Catalog.GetString("Минимум"));
		this.cbBright.AppendText(global::Mono.Unix.Catalog.GetString("Средний"));
		this.cbBright.AppendText(global::Mono.Unix.Catalog.GetString("Максимум"));
		this.cbBright.AppendText(global::Mono.Unix.Catalog.GetString("Авто"));
		this.cbBright.Name = "cbBright";
		this.cbBright.Active = 0;
		this.vbox8.Add(this.cbBright);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.cbBright]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.alignment8 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment8.Name = "alignment8";
		this.vbox8.Add(this.alignment8);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.alignment8]));
		w22.Position = 2;
		this.hbox2.Add(this.vbox8);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox8]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment5.Name = "alignment5";
		this.vbox7.Add(this.alignment5);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.alignment5]));
		w24.Position = 0;
		// Container child vbox7.Gtk.Box+BoxChild
		this.btnRight = new global::Gtk.Button();
		this.btnRight.CanFocus = true;
		this.btnRight.Name = "btnRight";
		this.btnRight.UseUnderline = true;
		global::Gtk.Image w25 = new global::Gtk.Image();
		this.btnRight.Image = w25;
		this.vbox7.Add(this.btnRight);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.btnRight]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.alignment6 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment6.Name = "alignment6";
		this.vbox7.Add(this.alignment6);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.alignment6]));
		w27.Position = 2;
		this.hbox2.Add(this.vbox7);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox7]));
		w28.PackType = ((global::Gtk.PackType)(1));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnUp = new global::Gtk.Button();
		this.btnUp.CanFocus = true;
		this.btnUp.Name = "btnUp";
		this.btnUp.UseUnderline = true;
		global::Gtk.Image w29 = new global::Gtk.Image();
		this.btnUp.Image = w29;
		this.vbox5.Add(this.btnUp);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.btnUp]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnSets = new global::Gtk.Button();
		this.btnSets.CanFocus = true;
		this.btnSets.Name = "btnSets";
		this.btnSets.UseUnderline = true;
		global::Gtk.Image w31 = new global::Gtk.Image();
		this.btnSets.Image = w31;
		this.vbox5.Add(this.btnSets);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.btnSets]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnDown = new global::Gtk.Button();
		this.btnDown.CanFocus = true;
		this.btnDown.Name = "btnDown";
		this.btnDown.UseUnderline = true;
		global::Gtk.Image w33 = new global::Gtk.Image();
		this.btnDown.Image = w33;
		this.vbox5.Add(this.btnDown);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.btnDown]));
		w34.Position = 2;
		w34.Expand = false;
		w34.Fill = false;
		this.hbox2.Add(this.vbox5);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox5]));
		w35.PackType = ((global::Gtk.PackType)(1));
		w35.Position = 3;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.vbox6.Add(this.alignment1);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment1]));
		w36.Position = 0;
		// Container child vbox6.Gtk.Box+BoxChild
		this.btnLeft = new global::Gtk.Button();
		this.btnLeft.CanFocus = true;
		this.btnLeft.Name = "btnLeft";
		this.btnLeft.UseUnderline = true;
		global::Gtk.Image w37 = new global::Gtk.Image();
		this.btnLeft.Image = w37;
		this.vbox6.Add(this.btnLeft);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.btnLeft]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.vbox6.Add(this.alignment2);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment2]));
		w39.Position = 2;
		this.hbox2.Add(this.vbox6);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox6]));
		w40.PackType = ((global::Gtk.PackType)(1));
		w40.Position = 4;
		w40.Expand = false;
		w40.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w41.Position = 2;
		w41.Expand = false;
		w41.Fill = false;
		w41.Padding = ((uint)(20));
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 527;
		this.DefaultHeight = 503;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
